/**
 * godot-project.ts — Godot 4 project.godot + default player pawn script.
 *
 * CLI --out must be a loadable Godot 4 project (File>Open Project), not a
 * sidecar pack of JSON + files/. ResourceLoader.load("res://…") resolves
 * against this project root.
 */

/** Stamped path of the pawn move script written next to world.tscn. */
export const PLAYER_SCRIPT_PATH = 'res://scripts/player.gd';
export const WORLD_RUNTIME_SCRIPT_PATH = 'res://scripts/world_runtime.gd';

/**
 * Minimal CharacterBody2D controller. Bound on the exported Player node so
 * F5 / headless run of world.tscn as main_scene is a walkable actor, not a
 * frozen camera over gizmos.
 */
export const PLAYER_MOVE_SCRIPT = `extends CharacterBody2D

const SPEED := 200.0

func _physics_process(_delta: float) -> void:
	var direction := Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	velocity = direction * SPEED
	move_and_slide()
`;

/**
 * F-54831eeb: shipped Area2D consumer for hazard / gate metadata.
 * Attach to hazard Area2Ds (or autoload). Reads metadata on body_entered.
 */
export const WORLD_RUNTIME_SCRIPT = `extends Node

func _ready() -> void:
	for child in get_tree().get_nodes_in_group("wf_hazards"):
		if child is Area2D and not child.body_entered.is_connected(_on_hazard_entered):
			child.body_entered.connect(_on_hazard_entered.bind(child))

func _on_hazard_entered(body: Node, area: Area2D) -> void:
	if body == null:
		return
	var effects := str(area.get_meta("effects", ""))
	var gate := str(area.get_meta("entry_gate", ""))
	if effects != "":
		print("[world_runtime] hazard ", area.name, " effects=", effects)
	if gate != "":
		print("[world_runtime] gate ", area.name, " conditions=", gate)
`;

/** Godot Key enum values used by the generated InputMap. */
const KEY = {
    left: 4194319,
    up: 4194320,
    right: 4194321,
    down: 4194322,
    a: 65,
    d: 68,
    s: 83,
    w: 87,
} as const;

function inputEventKey(keycode: number, physicalKeycode: number = 0): string {
    return (
        'Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"",' +
        `"device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,` +
        `"ctrl_pressed":false,"meta_pressed":false,"pressed":false,` +
        `"keycode":${keycode},"physical_keycode":${physicalKeycode},"key_label":0,` +
        `"unicode":0,"location":0,"echo":false,"script":null)`
    );
}

function inputAction(name: string, events: string[]): string {
    return (
        `${name}={\n` +
        `"deadzone": 0.5,\n` +
        `"events": [${events.join(', ')}]\n` +
        `}`
    );
}

function escapeCfg(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

export interface ProjectGodotOptions {
    /** config/name */
    name: string;
    /** run/main_scene — omit when --no-world-tscn. */
    mainScene?: string;
}

/**
 * Minimal Godot 4 `project.godot` (config_version=5). InputMap covers
 * ui_left/right/up/down (arrows + WASD) so the pawn script works on F5.
 */
export function buildProjectGodot(options: ProjectGodotOptions): string {
    const name = escapeCfg(options.name.trim() || 'World Forge');
    const lines: string[] = [
        '; Engine configuration file.',
        '; Generated by @world-forge/export-godot.',
        '',
        'config_version=5',
        '',
        '[application]',
        '',
        `config/name="${name}"`,
        'config/features=PackedStringArray("4.x")',
    ];
    if (options.mainScene) {
        lines.push(`run/main_scene="${escapeCfg(options.mainScene)}"`);
    }
    lines.push('');
    lines.push('[input]');
    lines.push('');
    lines.push(inputAction('ui_left', [inputEventKey(KEY.left), inputEventKey(KEY.a, KEY.a)]));
    lines.push(inputAction('ui_right', [inputEventKey(KEY.right), inputEventKey(KEY.d, KEY.d)]));
    lines.push(inputAction('ui_up', [inputEventKey(KEY.up), inputEventKey(KEY.w, KEY.w)]));
    lines.push(inputAction('ui_down', [inputEventKey(KEY.down), inputEventKey(KEY.s, KEY.s)]));
    lines.push('');
    lines.push('[rendering]');
    lines.push('');
    lines.push('renderer/rendering_method="gl_compatibility"');
    lines.push('');
    return lines.join('\n');
}
