// built-ins.ts — starter preset library

import type { RegionPreset, EncounterPreset } from './types.js';

// ── Region Presets ────────────────────────────────────────────

export const BUILTIN_REGION_PRESETS: RegionPreset[] = [
  {
    id: 'crypt-district',
    name: 'Crypt District',
    description: 'Undead-haunted tunnels with low morale and relentless pressure.',
    tags: ['undead', 'dungeon'],
    genre: 'fantasy',
    modes: ['dungeon', 'interior'],
    builtIn: true,
    regionTags: ['dark', 'cramped', 'undead'],
    controllingFaction: 'undead-horde',
    baseMetrics: { commerce: 5, morale: 15, safety: 10, stability: 20 },
    economyProfile: {
      supplyCategories: ['bones', 'cursed-relics'],
      scarcityDefaults: { weapons: 0.8, food: 0.9 },
    },
    factionPresences: [
      { factionId: 'undead-horde', influence: 85, alertLevel: 60 },
    ],
    pressureHotspots: [
      { pressureType: 'undead-surge', baseProbability: 0.7, tags: ['undead', 'swarm'] },
    ],
  },
  {
    id: 'market-ward',
    name: 'Market Ward',
    description: 'Bustling trade hub with high commerce and merchant guild oversight.',
    tags: ['trade', 'urban'],
    genre: 'fantasy',
    modes: ['district', 'world'],
    builtIn: true,
    regionTags: ['bustling', 'trade', 'crowded'],
    controllingFaction: 'merchant-guild',
    baseMetrics: { commerce: 90, morale: 65, safety: 55, stability: 70 },
    economyProfile: {
      supplyCategories: ['weapons', 'armor', 'potions', 'food', 'luxuries'],
      scarcityDefaults: { weapons: 0.2, food: 0.1 },
    },
    factionPresences: [
      { factionId: 'merchant-guild', influence: 75, alertLevel: 20 },
    ],
    pressureHotspots: [
      { pressureType: 'trade-dispute', baseProbability: 0.4, tags: ['economic', 'social'] },
    ],
  },
  {
    id: 'chapel-grounds',
    name: 'Chapel Grounds',
    description: 'Sacred ground with high morale, clergy influence, and divine unrest.',
    tags: ['sacred', 'religious'],
    genre: 'fantasy',
    modes: ['district', 'dungeon'],
    builtIn: true,
    regionTags: ['sacred', 'quiet', 'holy'],
    controllingFaction: 'clergy',
    baseMetrics: { commerce: 25, morale: 85, safety: 75, stability: 80 },
    economyProfile: {
      supplyCategories: ['healing', 'holy-water', 'tomes'],
      scarcityDefaults: { weapons: 0.7, healing: 0.1 },
    },
    factionPresences: [
      { factionId: 'clergy', influence: 90, alertLevel: 10 },
    ],
    pressureHotspots: [
      { pressureType: 'divine-incursion', baseProbability: 0.3, tags: ['divine', 'miracle'] },
    ],
  },
  {
    id: 'smuggler-dock',
    name: 'Smuggler Dock',
    description: 'Shady waterfront controlled by smugglers with low safety and contraband trade.',
    tags: ['criminal', 'waterfront'],
    genre: 'fantasy',
    modes: ['district', 'ocean'],
    builtIn: true,
    regionTags: ['shady', 'waterfront', 'dangerous'],
    controllingFaction: 'smuggler-ring',
    baseMetrics: { commerce: 60, morale: 35, safety: 15, stability: 25 },
    economyProfile: {
      supplyCategories: ['contraband', 'weapons', 'poisons', 'information'],
      scarcityDefaults: { healing: 0.6, food: 0.4 },
    },
    factionPresences: [
      { factionId: 'smuggler-ring', influence: 70, alertLevel: 45 },
    ],
    pressureHotspots: [
      { pressureType: 'contraband-raid', baseProbability: 0.5, tags: ['criminal', 'violence'] },
    ],
  },
  {
    id: 'ocean-port',
    name: 'Ocean Port',
    description: 'Coastal harbor with maritime trade, naval patrols, and sea-borne threats.',
    tags: ['port', 'maritime'],
    modes: ['ocean'],
    builtIn: true,
    regionTags: ['coastal', 'harbor', 'maritime'],
    controllingFaction: 'harbor-master',
    baseMetrics: { commerce: 75, morale: 55, safety: 45, stability: 60 },
    economyProfile: {
      supplyCategories: ['fish', 'salt', 'rope', 'trade-goods'],
      scarcityDefaults: { weapons: 0.5, food: 0.2 },
    },
    factionPresences: [
      { factionId: 'harbor-master', influence: 65, alertLevel: 30 },
    ],
    pressureHotspots: [
      { pressureType: 'pirate-raid', baseProbability: 0.5, tags: ['maritime', 'combat'] },
    ],
  },
  {
    id: 'space-station-hub',
    name: 'Space Station Hub',
    description: 'Pressurized station core with life support, docking bays, and corporate control.',
    tags: ['station', 'space'],
    modes: ['space'],
    builtIn: true,
    regionTags: ['pressurized', 'station', 'corporate'],
    controllingFaction: 'station-authority',
    baseMetrics: { commerce: 70, morale: 50, safety: 60, stability: 65 },
    economyProfile: {
      supplyCategories: ['oxygen', 'fuel', 'tech-parts', 'rations'],
      scarcityDefaults: { weapons: 0.6, food: 0.3 },
    },
    factionPresences: [
      { factionId: 'station-authority', influence: 80, alertLevel: 25 },
    ],
    pressureHotspots: [
      { pressureType: 'hull-breach', baseProbability: 0.3, tags: ['environmental', 'crisis'] },
    ],
  },
  {
    id: 'wilderness-camp',
    name: 'Wilderness Camp',
    description: 'Makeshift camp in untamed wilds with scavenged supplies and predator threats.',
    tags: ['camp', 'wild'],
    modes: ['wilderness'],
    builtIn: true,
    regionTags: ['wild', 'exposed', 'frontier'],
    controllingFaction: undefined,
    baseMetrics: { commerce: 10, morale: 40, safety: 25, stability: 30 },
    economyProfile: {
      supplyCategories: ['pelts', 'herbs', 'firewood'],
      scarcityDefaults: { weapons: 0.7, food: 0.5 },
    },
    factionPresences: [],
    pressureHotspots: [
      { pressureType: 'predator-attack', baseProbability: 0.6, tags: ['wildlife', 'combat'] },
    ],
  },
  {
    id: 'dungeon-vault',
    name: 'Dungeon Vault',
    description: 'Sealed treasure vault with ancient traps and guardian constructs.',
    tags: ['vault', 'dungeon'],
    modes: ['dungeon', 'interior'],
    builtIn: true,
    regionTags: ['sealed', 'trapped', 'treasure'],
    controllingFaction: 'guardian-constructs',
    baseMetrics: { commerce: 0, morale: 20, safety: 10, stability: 90 },
    economyProfile: {
      supplyCategories: ['gems', 'artifacts', 'gold'],
      scarcityDefaults: { weapons: 0.9, food: 1.0 },
    },
    factionPresences: [
      { factionId: 'guardian-constructs', influence: 100, alertLevel: 80 },
    ],
    pressureHotspots: [
      { pressureType: 'trap-activation', baseProbability: 0.8, tags: ['trap', 'mechanical'] },
    ],
  },
  {
    id: 'city-slum',
    name: 'City Slum',
    description: 'Overcrowded tenements with desperate residents, petty crime, and gang turf wars.',
    tags: ['slum', 'urban'],
    modes: ['district', 'world'],
    builtIn: true,
    regionTags: ['overcrowded', 'poor', 'dangerous'],
    controllingFaction: 'street-gang',
    baseMetrics: { commerce: 30, morale: 20, safety: 15, stability: 25 },
    economyProfile: {
      supplyCategories: ['scrap', 'street-food', 'cheap-weapons'],
      scarcityDefaults: { healing: 0.8, food: 0.6 },
    },
    factionPresences: [
      { factionId: 'street-gang', influence: 55, alertLevel: 50 },
    ],
    pressureHotspots: [
      { pressureType: 'gang-war', baseProbability: 0.6, tags: ['violence', 'turf'] },
    ],
  },
];

// ── Encounter Presets ─────────────────────────────────────────

export const BUILTIN_ENCOUNTER_PRESETS: EncounterPreset[] = [
  // ── Universal presets ──────────────────────────────────────
  {
    id: 'boss-encounter',
    name: 'Boss Encounter',
    description: 'Guaranteed scripted boss fight. No cooldown.',
    tags: ['boss', 'combat'],
    builtIn: true,
    encounterType: 'boss',
    enemyIds: [],
    probability: 1.0,
    cooldownTurns: 0,
    encounterTags: ['boss', 'scripted'],
  },
  {
    id: 'hazard-encounter',
    name: 'Hazard Encounter',
    description: 'Environmental trap or obstacle. Moderate probability, short cooldown.',
    tags: ['hazard', 'environmental'],
    builtIn: true,
    encounterType: 'hazard',
    enemyIds: [],
    probability: 0.6,
    cooldownTurns: 2,
    encounterTags: ['environmental', 'trap'],
  },
  {
    id: 'discovery-encounter',
    name: 'Discovery Encounter',
    description: 'Lore reveal or hidden reward. Low probability, long cooldown.',
    tags: ['discovery', 'exploration'],
    builtIn: true,
    encounterType: 'discovery',
    enemyIds: [],
    probability: 0.4,
    cooldownTurns: 5,
    encounterTags: ['lore', 'reward'],
  },
  // ── Mode-specific presets ──────────────────────────────────
  {
    id: 'dungeon-ambush',
    name: 'Dungeon Ambush',
    description: 'Enemies spring from the shadows in a confined space.',
    tags: ['ambush', 'dungeon'],
    modes: ['dungeon'],
    builtIn: true,
    encounterType: 'ambush',
    enemyIds: [],
    probability: 0.6,
    cooldownTurns: 3,
    encounterTags: ['ambush', 'underground'],
  },
  {
    id: 'district-brawl',
    name: 'Street Brawl',
    description: 'A fight breaks out in the streets — pick a side or stay clear.',
    tags: ['brawl', 'urban'],
    modes: ['district'],
    builtIn: true,
    encounterType: 'brawl',
    enemyIds: [],
    probability: 0.5,
    cooldownTurns: 3,
    encounterTags: ['urban', 'combat'],
  },
  {
    id: 'world-caravan-raid',
    name: 'Caravan Raid',
    description: 'Bandits attack a trade caravan on the open road.',
    tags: ['raid', 'overland'],
    modes: ['world'],
    builtIn: true,
    encounterType: 'caravan-raid',
    enemyIds: [],
    probability: 0.5,
    cooldownTurns: 5,
    encounterTags: ['military', 'large-scale'],
  },
  {
    id: 'ocean-pirate-attack',
    name: 'Pirate Attack',
    description: 'Corsairs close in on the open water, boarding hooks ready.',
    tags: ['pirate', 'maritime'],
    modes: ['ocean'],
    builtIn: true,
    encounterType: 'pirate',
    enemyIds: [],
    probability: 0.6,
    cooldownTurns: 3,
    encounterTags: ['maritime', 'combat'],
  },
  {
    id: 'space-boarding-action',
    name: 'Boarding Action',
    description: 'Hostiles breach the hull and force a close-quarters fight.',
    tags: ['boarding', 'space'],
    modes: ['space'],
    builtIn: true,
    encounterType: 'boarding',
    enemyIds: [],
    probability: 0.5,
    cooldownTurns: 4,
    encounterTags: ['space', 'tactical'],
  },
  {
    id: 'interior-haunt',
    name: 'Haunted Room',
    description: 'Something unseen stirs in a sealed room, rattling doors and snuffing candles.',
    tags: ['haunt', 'indoor'],
    modes: ['interior'],
    builtIn: true,
    encounterType: 'haunt',
    enemyIds: [],
    probability: 0.5,
    cooldownTurns: 3,
    encounterTags: ['supernatural', 'indoor'],
  },
  {
    id: 'wilderness-beast-hunt',
    name: 'Beast Hunt',
    description: 'A territorial predator stalks the party through dense terrain.',
    tags: ['beast', 'wilderness'],
    modes: ['wilderness'],
    builtIn: true,
    encounterType: 'beast',
    enemyIds: [],
    probability: 0.6,
    cooldownTurns: 3,
    encounterTags: ['wildlife', 'combat'],
  },
];
